apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-fe-app
  namespace: argo-cd
spec:
  project: app1-project
  source:
    repoURL: https://github.com/vinayellulla/app1-frontend-config.git
    targetRevision: HEAD
    path: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-ns
  syncPolicy:
    automated:
      prune: true # For deleting the resources 
      selfHeal: true # For self healing the resources 
